// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCULscAgByUhokkGhG-1iAV2uc4zsb8pI',
    appId: '1:1032875688013:web:f335873b3b8321da585c04',
    messagingSenderId: '1032875688013',
    projectId: 'smartexpense-ai-441ab',
    authDomain: 'smartexpense-ai-441ab.firebaseapp.com',
    storageBucket: 'smartexpense-ai-441ab.firebasestorage.app',
    measurementId: 'G-CZSPZ3SS27',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3lbfGhImEdJTNWPqsCvHe8GQisnUUQU8',
    appId: '1:1032875688013:android:b50a489c30dfe5b2585c04',
    messagingSenderId: '1032875688013',
    projectId: 'smartexpense-ai-441ab',
    storageBucket: 'smartexpense-ai-441ab.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHv-agN-xSiI3oCIPMMYORT0f0pPj7a8E',
    appId: '1:1032875688013:ios:ce178710f3c2515c585c04',
    messagingSenderId: '1032875688013',
    projectId: 'smartexpense-ai-441ab',
    storageBucket: 'smartexpense-ai-441ab.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseAi',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHv-agN-xSiI3oCIPMMYORT0f0pPj7a8E',
    appId: '1:1032875688013:ios:ce178710f3c2515c585c04',
    messagingSenderId: '1032875688013',
    projectId: 'smartexpense-ai-441ab',
    storageBucket: 'smartexpense-ai-441ab.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCULscAgByUhokkGhG-1iAV2uc4zsb8pI',
    appId: '1:1032875688013:web:73706f11c6ffef4f585c04',
    messagingSenderId: '1032875688013',
    projectId: 'smartexpense-ai-441ab',
    authDomain: 'smartexpense-ai-441ab.firebaseapp.com',
    storageBucket: 'smartexpense-ai-441ab.firebasestorage.app',
    measurementId: 'G-K5Y263XPXY',
  );
}
